// Offline relay regression fixtures: synthetic JSON/audio only; no private recordings; no live provider calls.
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {OhMyGptAudioAnalysis} from '../../apps/server/src/providers/ohmygpt/ohmygpt-audio-analysis.ts';
import {GEMINI_AUDIO_SCHEMA} from '../../apps/server/src/providers/google/gemini-audio-result.ts';
import {toRoundFailure} from '../../apps/server/src/application/round-errors.ts';
const key='synthetic-relay-key-not-a-secret';
const asset={asset_id:'11111111-2222-4333-8444-555555555555',media_type:'audio/wav',duration_ms:1000,sample_rate_hz:16000,channels:1};
const audio={asset,storage_key:asset.asset_id};
const payload=()=>({transcript:'本地测试。',segments:[{text:'本地测试。',emotion:'平静',units:[{text:'本地',granularity:'word',start_ms:0,end_ms:400},{text:'测试',granularity:'word',start_ms:400,end_ms:900}]}]});
const envelope=(body=payload(),extra={})=>({model:'gemini-3.8-flash',choices:[{index:0,finish_reason:'stop',message:{role:'assistant',content:JSON.stringify(body)}}],...extra});
const response=value=>new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json'}});
function harness({reply=envelope(),read,fetchImpl,timeoutMs=1000}={}){const calls=[],reads=[];const adapter=new OhMyGptAudioAnalysis({apiKey:key,timeoutMs,readAudio:async(...args)=>{reads.push(args);return read?read(...args):new Blob([Uint8Array.of(1,2,3)],{type:'audio/wav'});},fetch:async(...args)=>{calls.push(args);return fetchImpl?fetchImpl(...args):response(reply);}});return {adapter,calls,reads};}
async function failure(h,code,input=audio,signal=new AbortController().signal){await assert.rejects(h.adapter.analyze(input,{signal}),error=>{const safe=toRoundFailure(error,'analysis');assert.equal(safe.code,code);assert.ok(!JSON.stringify(safe).includes(key));return true;});}
test('one inline ordinary request uses only selected relay/model and compatible fresh schema',async()=>{const schemaBefore=JSON.stringify(GEMINI_AUDIO_SCHEMA);const h=harness();const result=await h.adapter.analyze(audio,{signal:new AbortController().signal});assert.equal(h.calls.length,1);assert.equal(h.reads.length,1);const [url,request]=h.calls[0];assert.equal(String(url),'https://api.ohmygpt.com/v1/chat/completions');assert.equal(request.method,'POST');assert.equal(request.redirect,'error');assert.equal(new Headers(request.headers).get('authorization'),'Bearer '+key);const body=JSON.parse(request.body);assert.equal(body.model,'gemini-3.8-flash');assert.equal(body.stream,false);assert.equal(body.store,false);assert.equal(body.n,1);assert.equal(body.max_tokens,4096);assert.equal(body.reasoning_effort,'low');assert.equal(body.response_format.type,'json_schema');assert.equal(body.response_format.json_schema.strict,true);assert.deepEqual(body.messages[0].content[1],{type:'input_audio',input_audio:{data:'AQID',format:'wav'}});for(const field of ['models','tools','plugins','previous_interaction','service_tier','provider','reasoning'])assert.ok(!(field in body));for(const secret of [key,asset.asset_id,'本地测试'])assert.ok(!request.body.includes(secret));assert.equal(JSON.stringify(GEMINI_AUDIO_SCHEMA),schemaBefore);const wireSchema=body.response_format.json_schema.schema;assert.ok(!JSON.stringify(wireSchema).includes('$schema'));assert.ok(!JSON.stringify(wireSchema).includes('anyOf'));const schemaNodes=[];const visitSchema=node=>{assert.ok(node&&typeof node==='object');assert.equal(typeof node.type,'string');schemaNodes.push(node);if(node.properties&&typeof node.properties==='object'){for(const value of Object.values(node.properties))visitSchema(value);}if(node.items){if(Array.isArray(node.items)){for(const value of node.items)visitSchema(value);}else visitSchema(node.items);}};visitSchema(wireSchema);assert.equal(schemaNodes.length,12);const granularity=wireSchema.properties.segments.items.properties.units.items.properties.granularity;assert.deepEqual(granularity,{enum:['word','character'],type:'string'});assert.equal(result.transcript,'本地测试。');assert.ok(JSON.stringify(result).includes('model-estimate-not-forced-alignment'));});
for(const [label,extra] of [['wrong model',{model:'gemini-3.7-flash'}],['unverified model alias',{model:'google/gemini-3.8-flash'}],['embedded error',{error:{message:key}}],['truncated output',{choices:[{index:0,finish_reason:'length',message:{role:'assistant',content:JSON.stringify(payload())}}]}],['tool request',{choices:[{index:0,finish_reason:'stop',message:{role:'assistant',content:JSON.stringify(payload()),tool_calls:[{}]}}]}],['refusal',{choices:[{index:0,finish_reason:'stop',message:{role:'assistant',content:JSON.stringify(payload()),refusal:'blocked'}}]}],['wrong role',{choices:[{index:0,finish_reason:'stop',message:{role:'user',content:JSON.stringify(payload())}}]}],['wrong index',{choices:[{index:1,finish_reason:'stop',message:{role:'assistant',content:JSON.stringify(payload())}}]}],['multiple choices',{choices:[envelope().choices[0],envelope().choices[0]]}],['empty content',{choices:[{index:0,finish_reason:'stop',message:{role:'assistant',content:''}}]}]])test('rejects '+label+' without retry/fallback',async()=>{const h=harness({reply:envelope(payload(),extra)});await failure(h,'invalid_result');assert.equal(h.calls.length,1);});
for(const [label,end] of [['zero',0],['missing',null],['outside',1100]])test('rejects '+label+' timing without inventing it',async()=>{const p=payload();p.segments[0].units[0].end_ms=end;const h=harness({reply:envelope(p)});await failure(h,'invalid_result');assert.equal(h.calls.length,1);});
test('already aborted has no read or request',async()=>{const h=harness(),c=new AbortController();c.abort();await failure(h,'cancelled',audio,c.signal);assert.equal(h.reads.length,0);assert.equal(h.calls.length,0);});
test('uncooperative local read is bounded',async()=>{const h=harness({timeoutMs:30,read:()=>new Promise(()=>{})});await failure(h,'timed_out');assert.equal(h.calls.length,0);});
test('uncooperative fetch is bounded',async()=>{const h=harness({timeoutMs:30,fetchImpl:()=>new Promise(()=>{})});await failure(h,'timed_out');assert.equal(h.calls.length,1);});
test('uncooperative response reader is bounded',async()=>{const h=harness({timeoutMs:30,fetchImpl:()=>new Response(new ReadableStream({pull:()=>new Promise(()=>{})}),{headers:{'Content-Type':'application/json'}})});await failure(h,'timed_out');assert.equal(h.calls.length,1);});
test('foreign exceptions cannot leak key or self-assign trusted code',async()=>{const h=harness({fetchImpl:()=>{throw Object.assign(new Error(key),{code:'invalid_result'});}});await failure(h,'provider_failed');assert.equal(h.calls.length,1);});
test('stream size is bounded without Content-Length',async()=>{const h=harness({fetchImpl:()=>new Response(new Uint8Array(1048577),{headers:{'Content-Type':'application/json'}})});await failure(h,'provider_failed');assert.equal(h.calls.length,1);});
test('invalid UTF8 is rejected',async()=>{const h=harness({fetchImpl:()=>new Response(Uint8Array.of(0xff),{headers:{'Content-Type':'application/json'}})});await failure(h,'provider_failed');});
test('HTTP errors fail once without using private body',async()=>{const h=harness({fetchImpl:()=>new Response(key,{status:401})});await failure(h,'provider_failed');assert.equal(h.calls.length,1);});
test('unsupported MIME rejected before reading',async()=>{const h=harness();await failure(h,'invalid_input',{...audio,asset:{...asset,media_type:'audio/webm'}});assert.equal(h.calls.length,0);assert.equal(h.reads.length,0);});
test('silence explicitly lacks emotion',async()=>{const h=harness({reply:envelope({transcript:'',segments:[]})});const r=await h.adapter.analyze(audio,{signal:new AbortController().signal});assert.equal(r.transcript,'');assert.equal(r.capabilities.emotion.status,'unavailable');});
